<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../MobilityBridge.Application/MobilityBridge.Application.csproj" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
    <PackageReference Include="NetTopologySuite" Version="2.6.0" />
    <PackageReference Include="RabbitMQ.Client" Version="7.1.2" />
    <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="9.0.4" />
    <PackageReference Include="Microsoft.Orleans.Server" Version="9.1.2" />
  </ItemGroup>
</Project>
